package com.jakefear.aipublisher.output;

import com.jakefear.aipublisher.config.OutputProperties;
import com.jakefear.aipublisher.document.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("WikiOutputService")
class WikiOutputServiceTest {

    @TempDir
    Path tempDir;

    private OutputProperties outputProperties;
    private WikiOutputService service;

    @BeforeEach
    void setUp() {
        outputProperties = new OutputProperties();
        outputProperties.setDirectory(tempDir.toString());
        outputProperties.setFileExtension(".md");
        service = new WikiOutputService(outputProperties);
    }

    @Nested
    @DisplayName("Write Document")
    class WriteDocument {

        @Test
        @DisplayName("Writes document to output directory")
        void writesDocumentToOutputDirectory() throws IOException {
            // Arrange
            PublishingDocument document = createCompletedDocument("ApacheKafka");

            // Act
            Path result = service.writeDocument(document);

            // Assert
            assertTrue(Files.exists(result));
            assertEquals("ApacheKafka.md", result.getFileName().toString());

            String content = Files.readString(result);
            assertTrue(content.contains("ApacheKafka"));
        }

        @Test
        @DisplayName("Creates output directory if not exists")
        void createsOutputDirectoryIfNotExists() throws IOException {
            // Arrange
            Path newDir = tempDir.resolve("newsubdir");
            outputProperties.setDirectory(newDir.toString());
            WikiOutputService newService = new WikiOutputService(outputProperties);
            PublishingDocument document = createCompletedDocument("TestPage");

            // Act
            Path result = newService.writeDocument(document);

            // Assert
            assertTrue(Files.exists(newDir));
            assertTrue(Files.exists(result));
        }

        @Test
        @DisplayName("Includes metadata comment in output")
        void includesMetadataCommentInOutput() throws IOException {
            // Arrange
            PublishingDocument document = createCompletedDocument("TestArticle");

            // Act
            Path result = service.writeDocument(document);
            String content = Files.readString(result);

            // Assert
            assertTrue(content.contains("Generated by AI Publisher"));
            assertTrue(content.contains("Title:"));
            assertTrue(content.contains("Quality Score:"));
        }

        @Test
        @DisplayName("Throws exception when no final article")
        void throwsExceptionWhenNoFinalArticle() {
            // Arrange
            TopicBrief brief = TopicBrief.simple("Test", "testers", 500);
            PublishingDocument document = new PublishingDocument(brief);
            // Don't set final article

            // Act & Assert
            assertThrows(IllegalStateException.class, () -> service.writeDocument(document));
        }

        @Test
        @DisplayName("File ends with newline")
        void fileEndsWithNewline() throws IOException {
            // Arrange
            PublishingDocument document = createCompletedDocument("TestPage");

            // Act
            Path result = service.writeDocument(document);
            String content = Files.readString(result);

            // Assert
            assertTrue(content.endsWith("\n"));
        }
    }

    @Nested
    @DisplayName("Discover Existing Pages")
    class DiscoverExistingPages {

        @Test
        @DisplayName("Returns empty set for empty directory")
        void returnsEmptySetForEmptyDirectory() {
            // Act
            Set<String> pages = service.discoverExistingPages();

            // Assert
            assertTrue(pages.isEmpty());
        }

        @Test
        @DisplayName("Discovers .md files in directory")
        void discoversMdFilesInDirectory() throws IOException {
            // Arrange
            Files.writeString(tempDir.resolve("ApacheKafka.md"), "# Kafka");
            Files.writeString(tempDir.resolve("EventStreaming.md"), "# Events");
            Files.writeString(tempDir.resolve("MessageQueue.md"), "# Queues");

            // Act
            Set<String> pages = service.discoverExistingPages();

            // Assert
            assertEquals(3, pages.size());
            assertTrue(pages.contains("ApacheKafka"));
            assertTrue(pages.contains("EventStreaming"));
            assertTrue(pages.contains("MessageQueue"));
        }

        @Test
        @DisplayName("Ignores non-.md files")
        void ignoresNonMdFiles() throws IOException {
            // Arrange
            Files.writeString(tempDir.resolve("WikiPage.md"), "# Page");
            Files.writeString(tempDir.resolve("readme.txt"), "readme");
            Files.writeString(tempDir.resolve("config.json"), "{}");
            Files.createDirectory(tempDir.resolve("subdir"));

            // Act
            Set<String> pages = service.discoverExistingPages();

            // Assert
            assertEquals(1, pages.size());
            assertTrue(pages.contains("WikiPage"));
        }

        @Test
        @DisplayName("Returns empty set for non-existent directory")
        void returnsEmptySetForNonExistentDirectory() {
            // Arrange
            outputProperties.setDirectory(tempDir.resolve("nonexistent").toString());
            WikiOutputService newService = new WikiOutputService(outputProperties);

            // Act
            Set<String> pages = newService.discoverExistingPages();

            // Assert
            assertTrue(pages.isEmpty());
        }

        @Test
        @DisplayName("Returns sorted list")
        void returnsSortedList() throws IOException {
            // Arrange
            Files.writeString(tempDir.resolve("Zebra.md"), "# Z");
            Files.writeString(tempDir.resolve("Alpha.md"), "# A");
            Files.writeString(tempDir.resolve("Middle.md"), "# M");

            // Act
            List<String> pages = service.getExistingPagesList();

            // Assert
            assertEquals(List.of("Alpha", "Middle", "Zebra"), pages);
        }
    }

    @Nested
    @DisplayName("Page Exists")
    class PageExists {

        @Test
        @DisplayName("Returns true for existing page")
        void returnsTrueForExistingPage() throws IOException {
            // Arrange
            Files.writeString(tempDir.resolve("ExistingPage.md"), "# Content");

            // Act & Assert
            assertTrue(service.pageExists("ExistingPage"));
        }

        @Test
        @DisplayName("Returns false for non-existent page")
        void returnsFalseForNonExistentPage() {
            // Act & Assert
            assertFalse(service.pageExists("NonExistentPage"));
        }
    }

    @Nested
    @DisplayName("Generate Filename")
    class GenerateFilename {

        @Test
        @DisplayName("Generates filename with .md extension")
        void generatesFilenameWithExtension() {
            // Act & Assert
            assertEquals("ApacheKafka.md", service.generateFilename("ApacheKafka"));
        }

        @Test
        @DisplayName("Converts spaces to CamelCase")
        void convertsSpacesToCamelCase() {
            // Act & Assert
            assertEquals("ApacheKafka.md", service.generateFilename("Apache Kafka"));
            assertEquals("GitBranchingStrategies.md", service.generateFilename("Git branching strategies"));
        }

        @Test
        @DisplayName("Converts hyphens to CamelCase")
        void convertsHyphensToCamelCase() {
            // Act & Assert
            assertEquals("EventDrivenArchitecture.md", service.generateFilename("event-driven-architecture"));
        }

        @Test
        @DisplayName("Converts underscores to CamelCase")
        void convertsUnderscoresToCamelCase() {
            // Act & Assert
            assertEquals("MessageQueue.md", service.generateFilename("message_queue"));
        }

        @Test
        @DisplayName("Capitalizes first letter of CamelCase input")
        void capitalizesFirstLetterOfCamelCaseInput() {
            // Act & Assert
            assertEquals("ApacheKafka.md", service.generateFilename("apacheKafka"));
        }

        @Test
        @DisplayName("Handles null and blank input")
        void handlesNullAndBlankInput() {
            // Act & Assert
            assertEquals("UnnamedPage.md", service.generateFilename(null));
            assertEquals("UnnamedPage.md", service.generateFilename(""));
            assertEquals("UnnamedPage.md", service.generateFilename("   "));
        }
    }

    @Nested
    @DisplayName("Format For Output")
    class FormatForOutput {

        @Test
        @DisplayName("Includes article content")
        void includesArticleContent() {
            // Arrange
            FinalArticle article = createFinalArticle("## Test Title\n\nContent here.");

            // Act
            String result = service.formatForOutput(article);

            // Assert
            assertTrue(result.contains("## Test Title"));
            assertTrue(result.contains("Content here."));
        }

        @Test
        @DisplayName("Includes metadata comment")
        void includesMetadataComment() {
            // Arrange
            FinalArticle article = createFinalArticle("Content");

            // Act
            String result = service.formatForOutput(article);

            // Assert
            assertTrue(result.contains("<!--"));
            assertTrue(result.contains("-->"));
            assertTrue(result.contains("Generated by AI Publisher"));
        }

        @Test
        @DisplayName("Includes quality score in comment")
        void includesQualityScoreInComment() {
            // Arrange
            FinalArticle article = createFinalArticle("Content");

            // Act
            String result = service.formatForOutput(article);

            // Assert
            assertTrue(result.contains("Quality Score: 0.85"));
        }

        @Test
        @DisplayName("Includes edit summary in comment")
        void includesEditSummaryInComment() {
            // Arrange
            FinalArticle article = new FinalArticle(
                    "Content",
                    DocumentMetadata.create("Title", "Summary"),
                    "Fixed typos and improved clarity",
                    0.9,
                    List.of()
            );

            // Act
            String result = service.formatForOutput(article);

            // Assert
            assertTrue(result.contains("Fixed typos and improved clarity"));
        }
    }

    @Nested
    @DisplayName("Ensure Output Directory")
    class EnsureOutputDirectory {

        @Test
        @DisplayName("Creates directory if not exists")
        void createsDirectoryIfNotExists() throws IOException {
            // Arrange
            Path newDir = tempDir.resolve("newdir");
            outputProperties.setDirectory(newDir.toString());
            WikiOutputService newService = new WikiOutputService(outputProperties);

            // Act
            Path result = newService.ensureOutputDirectory();

            // Assert
            assertTrue(Files.exists(result));
            assertTrue(Files.isDirectory(result));
        }

        @Test
        @DisplayName("Returns existing directory")
        void returnsExistingDirectory() throws IOException {
            // Arrange - tempDir already exists

            // Act
            Path result = service.ensureOutputDirectory();

            // Assert
            assertEquals(tempDir, result);
            assertTrue(Files.exists(result));
        }

        @Test
        @DisplayName("Creates nested directories")
        void createsNestedDirectories() throws IOException {
            // Arrange
            Path nestedDir = tempDir.resolve("a/b/c/output");
            outputProperties.setDirectory(nestedDir.toString());
            WikiOutputService newService = new WikiOutputService(outputProperties);

            // Act
            Path result = newService.ensureOutputDirectory();

            // Assert
            assertTrue(Files.exists(result));
        }
    }

    // Helper methods

    private PublishingDocument createCompletedDocument(String pageName) {
        TopicBrief brief = TopicBrief.simple(pageName.replaceAll("([A-Z])", " $1").trim(), "developers", 500);
        PublishingDocument document = new PublishingDocument(brief);

        // Set required fields for a completed document
        document.transitionTo(DocumentState.RESEARCHING);
        document.setResearchBrief(new ResearchBrief(
                List.of(KeyFact.unsourced("Fact 1"), KeyFact.unsourced("Fact 2"), KeyFact.unsourced("Fact 3")),
                List.of(),
                List.of("Intro", "Main"),
                List.of(),
                java.util.Map.of(),
                List.of()
        ));

        document.transitionTo(DocumentState.DRAFTING);
        document.setDraft(new ArticleDraft(
                "## " + pageName + "\n\nContent about " + pageName,
                "Summary of " + pageName,
                List.of(),
                List.of(),
                java.util.Map.of()
        ));

        document.transitionTo(DocumentState.FACT_CHECKING);
        document.setFactCheckReport(new FactCheckReport(
                document.getDraft().markdownContent(),
                List.of(),
                List.of(),
                List.of(),
                ConfidenceLevel.HIGH,
                RecommendedAction.APPROVE
        ));

        document.transitionTo(DocumentState.EDITING);
        document.setFinalArticle(new FinalArticle(
                "## " + pageName + "\n\nFinal content about " + pageName,
                DocumentMetadata.create(pageName, "Summary of " + pageName),
                "Article edited for publication",
                0.85,
                List.of()
        ));

        return document;
    }

    private FinalArticle createFinalArticle(String content) {
        return new FinalArticle(
                content,
                DocumentMetadata.create("Test Title", "Test summary"),
                "Test edit summary",
                0.85,
                List.of()
        );
    }
}
